// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: artifact-registry.proto

package artifact_registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactData_ArtifactType int32

const (
	ArtifactData_MODEL   ArtifactData_ArtifactType = 0
	ArtifactData_METRICS ArtifactData_ArtifactType = 1
	ArtifactData_DATASET ArtifactData_ArtifactType = 2
	ArtifactData_OTHER   ArtifactData_ArtifactType = 3
)

// Enum value maps for ArtifactData_ArtifactType.
var (
	ArtifactData_ArtifactType_name = map[int32]string{
		0: "MODEL",
		1: "METRICS",
		2: "DATASET",
		3: "OTHER",
	}
	ArtifactData_ArtifactType_value = map[string]int32{
		"MODEL":   0,
		"METRICS": 1,
		"DATASET": 2,
		"OTHER":   3,
	}
)

func (x ArtifactData_ArtifactType) Enum() *ArtifactData_ArtifactType {
	p := new(ArtifactData_ArtifactType)
	*p = x
	return p
}

func (x ArtifactData_ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactData_ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_registry_proto_enumTypes[0].Descriptor()
}

func (ArtifactData_ArtifactType) Type() protoreflect.EnumType {
	return &file_artifact_registry_proto_enumTypes[0]
}

func (x ArtifactData_ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactData_ArtifactType.Descriptor instead.
func (ArtifactData_ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_artifact_registry_proto_rawDescGZIP(), []int{1, 0}
}

type MLArtifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MLArtifact) Reset() {
	*x = MLArtifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artifact_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLArtifact) ProtoMessage() {}

func (x *MLArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLArtifact.ProtoReflect.Descriptor instead.
func (*MLArtifact) Descriptor() ([]byte, []int) {
	return file_artifact_registry_proto_rawDescGZIP(), []int{0}
}

func (x *MLArtifact) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ArtifactData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri          string                    `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Version      string                    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ExecutionId  string                    `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ArtifactType ArtifactData_ArtifactType `protobuf:"varint,5,opt,name=artifact_type,json=artifactType,proto3,enum=artifact_registry.ArtifactData_ArtifactType" json:"artifact_type,omitempty"`
	Metadata     *structpb.Struct          `protobuf:"bytes,6,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
}

func (x *ArtifactData) Reset() {
	*x = ArtifactData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artifact_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactData) ProtoMessage() {}

func (x *ArtifactData) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactData.ProtoReflect.Descriptor instead.
func (*ArtifactData) Descriptor() ([]byte, []int) {
	return file_artifact_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactData) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ArtifactData) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ArtifactData) GetArtifactType() ArtifactData_ArtifactType {
	if x != nil {
		return x.ArtifactType
	}
	return ArtifactData_MODEL
}

func (x *ArtifactData) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ArtifactsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artifacts []*ArtifactData `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *ArtifactsResponse) Reset() {
	*x = ArtifactsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artifact_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsResponse) ProtoMessage() {}

func (x *ArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactsResponse) GetArtifacts() []*ArtifactData {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type Workspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_artifact_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_artifact_registry_proto_rawDescGZIP(), []int{3}
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_artifact_registry_proto protoreflect.FileDescriptor

var file_artifact_registry_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x2d, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0a, 0x4d, 0x4c,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xcb, 0x02, 0x0a, 0x0c, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x69, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x51,
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x22, 0x3e, 0x0a, 0x0c, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x4f, 0x44, 0x45, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43,
	0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x41, 0x54, 0x41, 0x53, 0x45, 0x54, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x03, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x11, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x09,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x15, 0x5a,
	0x13, 0x2f, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_artifact_registry_proto_rawDescOnce sync.Once
	file_artifact_registry_proto_rawDescData = file_artifact_registry_proto_rawDesc
)

func file_artifact_registry_proto_rawDescGZIP() []byte {
	file_artifact_registry_proto_rawDescOnce.Do(func() {
		file_artifact_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_artifact_registry_proto_rawDescData)
	})
	return file_artifact_registry_proto_rawDescData
}

var file_artifact_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_artifact_registry_proto_goTypes = []interface{}{
	(ArtifactData_ArtifactType)(0), // 0: artifact_registry.ArtifactData.ArtifactType
	(*MLArtifact)(nil),             // 1: artifact_registry.MLArtifact
	(*ArtifactData)(nil),           // 2: artifact_registry.ArtifactData
	(*ArtifactsResponse)(nil),      // 3: artifact_registry.ArtifactsResponse
	(*Workspace)(nil),              // 4: artifact_registry.Workspace
	(*structpb.Struct)(nil),        // 5: google.protobuf.Struct
}
var file_artifact_registry_proto_depIdxs = []int32{
	0, // 0: artifact_registry.ArtifactData.artifact_type:type_name -> artifact_registry.ArtifactData.ArtifactType
	5, // 1: artifact_registry.ArtifactData.metadata:type_name -> google.protobuf.Struct
	2, // 2: artifact_registry.ArtifactsResponse.artifacts:type_name -> artifact_registry.ArtifactData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_artifact_registry_proto_init() }
func file_artifact_registry_proto_init() {
	if File_artifact_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_artifact_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLArtifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artifact_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artifact_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_artifact_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_artifact_registry_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_artifact_registry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_registry_proto_goTypes,
		DependencyIndexes: file_artifact_registry_proto_depIdxs,
		EnumInfos:         file_artifact_registry_proto_enumTypes,
		MessageInfos:      file_artifact_registry_proto_msgTypes,
	}.Build()
	File_artifact_registry_proto = out.File
	file_artifact_registry_proto_rawDesc = nil
	file_artifact_registry_proto_goTypes = nil
	file_artifact_registry_proto_depIdxs = nil
}
